"use client";
import { useEffect, useState } from "react";
import { CalendarDays, GraduationCap, Wallet, ClipboardCheck } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import Panel from "@/components/Panel";
import { useTickets, addTicket, updateTicket, statusColor } from "@/lib/tickets";

const NAV = ["Dashboard", "Timetable", "Attendance", "Fees", "Results", "Exams", "Notes", "My Tickets"];

export default function StudentDashboard() {
  const [tab, setTab] = useState("Dashboard");
  const [me, setMe] = useState("Navlani Jaykrishna");
  const tickets = useTickets();
  useEffect(() => {
    try { const raw = sessionStorage.getItem("sou_user"); if (raw) { const u = JSON.parse(raw); if (u.fullName) setMe(u.fullName); } } catch {}
  }, []);
  const myFirst = me.split(" ")[0].toLowerCase();
  const mine = tickets.filter((t) => t.creator.toLowerCase().includes(myFirst) || me.toLowerCase().includes(t.creator.split(" ")[0].toLowerCase()));

  const raise = () => {
    const subject = window.prompt("Describe your issue / query:");
    if (!subject) return;
    addTicket({ subject: subject.slice(0, 60), description: subject, category: "GENERAL", creator: me, priority: "MEDIUM" });
    setTab("My Tickets");
  };

  const downloadReceipt = () => {
    const now = new Date().toLocaleString();
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>SOU Fee Receipt</title>
    <style>body{font-family:Arial,sans-serif;max-width:640px;margin:40px auto;color:#111}
    .head{text-align:center;border-bottom:3px solid #6d28d9;padding-bottom:12px}.head h1{color:#6d28d9;margin:0}
    table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:10px;text-align:left}
    th{background:#f3e8ff}.foot{margin-top:24px;font-size:12px;color:#666;text-align:center}</style></head>
    <body><div class="head"><h1>Silver Oak University</h1><p>Official Fee Receipt</p></div>
    <table><tr><th>Student Name</th><td>Navlani Jaykrishna Satishkumar</td></tr><tr><th>Enrollment No.</th><td>SOU2023CSE69</td></tr>
    <tr><th>Program</th><td>B.Tech CSE - Semester 5</td></tr><tr><th>Receipt No.</th><td>RC-2026-000069</td></tr>
    <tr><th>Date</th><td>${now}</td></tr><tr><th>Total Fees</th><td>Rs 1,20,000</td></tr><tr><th>Amount Paid</th><td>Rs 90,000</td></tr>
    <tr><th>Balance Due</th><td>Rs 30,000 (due 15 Aug 2026)</td></tr><tr><th>Payment Mode</th><td>Online</td></tr></table>
    <div class="foot">Computer-generated receipt. Generated by SOU AI HelpDesk Pro.</div></body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "SOU-Fee-Receipt.html";
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  };

  const timetable = [["09:00", "Data Structures", "Akshay Sir", "A-301"], ["10:00", "DBMS", "Sagar Sir", "A-302"], ["11:00", "OS Lab", "Akshay Sir", "Lab-2"]];
  const attendance = [["Data Structures", "88%"], ["DBMS", "92%"], ["Operating Systems", "79%"], ["Machine Learning", "95%"]];
  const results = [["Data Structures", 28, 66, "A"], ["DBMS", 26, 71, "A"], ["Operating Systems", 24, 58, "B+"]];
  const notes = [["DSA - Trees.pdf", "PDF"], ["DBMS Normalization.ppt", "PPT"], ["OS Scheduling.mp4", "VIDEO"], ["Assignment 3.pdf", "ASSIGNMENT"]];

  return (
    <DashboardShell role="Student" name="Navlani Jaykrishna" nav={NAV} activeNav={tab} onNavSelect={setTab}
      stats={[
        { label: "CGPA", value: "8.4", icon: GraduationCap },
        { label: "Attendance", value: "88%", icon: ClipboardCheck },
        { label: "Pending Fees", value: "Rs 30k", icon: Wallet },
        { label: "My Tickets", value: String(mine.length), icon: CalendarDays },
      ]}>

      {(tab === "Dashboard" || tab === "Timetable") && (
        <Panel title="Today's Timetable">
          <div className="space-y-2 text-sm">
            {timetable.map((r, i) => (
              <div key={i} className="flex items-center justify-between glass px-4 py-3">
                <span className="font-mono text-brand-light">{r[0]}</span><span className="flex-1 px-3">{r[1]}</span>
                <span className="text-[var(--muted)]">{r[2]}</span><span className="ml-3 text-xs glass px-2 py-1">{r[3]}</span>
              </div>
            ))}
          </div>
        </Panel>
      )}

      {(tab === "Dashboard" || tab === "Attendance") && (
        <div className="mt-6"><Panel title="Attendance by Subject">
          <div className="space-y-3">
            {attendance.map(([s, p]) => (
              <div key={s}>
                <div className="flex justify-between text-sm mb-1"><span>{s}</span><span className="text-brand-light">{p}</span></div>
                <div className="h-2 rounded-full bg-white/10 overflow-hidden"><div className="h-full bg-gradient-to-r from-brand to-brand-cyan" style={{ width: p }} /></div>
              </div>
            ))}
          </div>
        </Panel></div>
      )}

      {(tab === "Dashboard" || tab === "Fees") && (
        <div className="mt-6"><Panel title="Fees">
          <div className="grid grid-cols-3 gap-3 text-center text-sm">
            <div className="glass p-4"><div className="text-lg font-bold">Rs 1.2L</div><div className="text-[var(--muted)]">Total</div></div>
            <div className="glass p-4"><div className="text-lg font-bold text-emerald-400">Rs 90k</div><div className="text-[var(--muted)]">Paid</div></div>
            <div className="glass p-4"><div className="text-lg font-bold text-rose-400">Rs 30k</div><div className="text-[var(--muted)]">Pending</div></div>
          </div>
          <button onClick={downloadReceipt} className="mt-4 px-4 py-2 rounded-full bg-brand text-white text-sm hover:bg-brand-light">Download Receipt</button>
        </Panel></div>
      )}

      {tab === "Results" && (
        <Panel title="Results - Semester 5">
          <table className="w-full text-sm">
            <thead><tr className="text-[var(--muted)] text-left"><th className="py-2">Subject</th><th>Internal</th><th>External</th><th>Grade</th></tr></thead>
            <tbody>{results.map((r, i) => <tr key={i} className="border-t border-[var(--border)]"><td className="py-2">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td className="text-brand-light">{r[3]}</td></tr>)}</tbody>
          </table>
          <div className="mt-4 flex gap-6 text-sm"><span>SGPA: <b className="text-brand-light">8.4</b></span><span>CGPA: <b className="text-brand-light">8.4</b></span></div>
        </Panel>
      )}

      {tab === "Exams" && (
        <Panel title="Exam Timetable">
          <div className="glass px-4 py-3 text-sm flex justify-between"><span>Machine Learning - End Sem</span><span className="text-[var(--muted)]">20 Nov 2026</span><span className="text-brand-light">Seat H1-042</span></div>
          <p className="text-xs text-[var(--muted)] mt-3">Venue: Exam Hall 1 | Duration: 180 min</p>
        </Panel>
      )}

      {tab === "Notes" && (
        <Panel title="Notes & Study Material">
          <div className="grid sm:grid-cols-2 gap-3 text-sm">
            {notes.map((n, i) => (
              <button key={i} onClick={() => alert("Downloading " + n[0] + "...")} className="glass px-4 py-3 flex items-center justify-between text-left hover:bg-brand/10">
                <span>{n[0]}</span><span className="text-xs px-2 py-1 rounded-full bg-brand/20 text-brand-light">{n[1]}</span>
              </button>
            ))}
          </div>
        </Panel>
      )}

      {tab === "My Tickets" && (
        <Panel title="My Tickets">
          <button onClick={raise} className="mb-3 px-4 py-2 rounded-full bg-brand text-white text-sm hover:bg-brand-light">+ Raise a Ticket</button>
          <div className="space-y-2 text-sm">
            {mine.map((t) => (
              <div key={t.code} className="glass px-4 py-3 flex items-center justify-between">
                <div><span className="font-mono text-brand-light">{t.code}</span><div className="text-[var(--muted)]">{t.subject}</div>
                  {t.note && <div className="text-xs text-brand-light mt-1">{t.note}</div>}</div>
                <div className="flex items-center gap-2">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${statusColor(t.status)}`}>{t.status}</span>
                  {(t.status === "Resolved" || t.status === "Closed") && <button onClick={() => updateTicket(t.code, { status: "Reopened", note: "Reopened by student" })} className="text-xs px-3 py-1 rounded-full glass">Reopen</button>}
                </div>
              </div>
            ))}
            {mine.length === 0 && <p className="text-[var(--muted)]">You have no tickets. Use the AI assistant or "Raise a Ticket".</p>}
          </div>
        </Panel>
      )}

    </DashboardShell>
  );
}
