"use client";
import FeedbackPanel from "@/components/FeedbackPanel";
import GrievancePanel from "@/components/GrievancePanel";
import FinancePanel from "@/components/FinancePanel";
import QRPanel from "@/components/QRPanel";
import BookingPanel from "@/components/BookingPanel";
import { useEffect, useState } from "react";
import { CalendarDays, GraduationCap, Wallet, ClipboardCheck } from "lucide-react";
import DashboardShell from "@/components/DashboardShell";
import Panel from "@/components/Panel";
import ClassroomPanel from "@/components/ClassroomPanel";
import CRAttendance from "@/components/CRAttendance";
import StudyPanel from "@/components/StudyPanel";
import ClassGroupPanel from "@/components/ClassGroupPanel";
import TutorPanel from "@/components/TutorPanel";
import FunPanel from "@/components/FunPanel";
import ResultsPanel, { useMyResults, averageLabel } from "@/components/ResultsPanel";
import { useTickets, addTicket, updateTicket, statusColor } from "@/lib/tickets";
import { useCRs, CRAssignment } from "@/lib/attendance";

export default function StudentDashboard() {
  const [tab, setTab] = useState("Dashboard");
  const [me, setMe] = useState({ name: "Navlani Jaykrishna", enrollmentNo: "SOU2023CSE69" });
  const tickets = useTickets();
  const crs = useCRs();
  const myResults = useMyResults();

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("sou_user");
      if (raw) { const u = JSON.parse(raw); setMe({ name: u.fullName || "Student", enrollmentNo: u.loginId || "" }); }
    } catch {}
  }, []);

  const myCr: CRAssignment[] = crs.filter((c) => c.enrollmentNo.toLowerCase() === me.enrollmentNo.toLowerCase());
  const isCR = myCr.length > 0;

  const NAV = ["Dashboard", "Timetable", "Classroom", "Fees", "Results", "Study Plan", "Tutor", "Class Group", "Exams", "Notes", "My Tickets", "GreenReserve", "QR Attendance", "Feedback", "Grievance", "Fun Zone"];
  if (isCR) NAV.splice(2, 0, "Mark Attendance");

  const first = me.name.split(" ")[0].toLowerCase();
  const mine = tickets.filter((t) => t.creator.toLowerCase().includes(first) || me.name.toLowerCase().includes(t.creator.split(" ")[0].toLowerCase()));

  const raise = () => {
    const subject = window.prompt("Describe your issue / query:");
    if (!subject) return;
    addTicket({ subject: subject.slice(0, 60), description: subject, category: "GENERAL", creator: me.name, priority: "MEDIUM" });
    setTab("My Tickets");
  };

  const downloadReceipt = () => {
    const now = new Date().toLocaleString();
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>SOU Fee Receipt</title>
    <style>body{font-family:Arial,sans-serif;max-width:640px;margin:40px auto;color:#111}
    .head{text-align:center;border-bottom:3px solid #6d28d9;padding-bottom:12px}.head h1{color:#6d28d9;margin:0}
    table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:10px;text-align:left}
    th{background:#f3e8ff}.foot{margin-top:24px;font-size:12px;color:#666;text-align:center}
    .warn{margin-top:20px;padding:12px;border:1px solid #f0c000;background:#fffbe6;font-size:13px}</style></head>
    <body><div class="head"><h1>Silver Oak University</h1><p>Fee summary — for your own reference</p></div>
    <table><tr><th>Student Name</th><td>${me.name}</td></tr><tr><th>Enrollment No.</th><td>${me.enrollmentNo}</td></tr>
    <tr><th>Date generated</th><td>${now}</td></tr></table>
    <div class="warn"><b>This is not an official receipt.</b> It is a summary printed from the
    portal for your own reference. The figures above your fee record on screen are the
    authoritative ones, and an official receipt comes from the Accounts Office.</div>
    <div class="foot">Generated by SOU AI HelpDesk Pro.</div></body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "SOU-Fee-Summary.html";
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  };

  const timetable = [["09:00", "Data Structures", "Prof. R. Mehta", "A-301"], ["10:00", "DBMS", "Prof. S. Iyer", "A-302"], ["11:00", "OS Lab", "Prof. R. Mehta", "Lab-2"]];
  const notes = [["DSA - Trees.pdf", "PDF"], ["DBMS Normalization.ppt", "PPT"], ["OS Scheduling.mp4", "VIDEO"], ["Assignment 3.pdf", "ASSIGNMENT"]];

  return (
    <DashboardShell role="Student" name={me.name} nav={NAV} activeNav={tab} onNavSelect={setTab}
      stats={[
        { label: "Average score", value: averageLabel(myResults.plan), icon: GraduationCap },
        { label: isCR ? "CR Subjects" : "Courses", value: isCR ? String(myCr.length) : "4", icon: ClipboardCheck },
        { label: "Pending Fees", value: "Check with accounts", icon: Wallet },
        { label: "My Tickets", value: String(mine.length), icon: CalendarDays },
      ]}>

      {(tab === "Dashboard" || tab === "Timetable") && (
        <Panel title="Today's timetable"
          hint="Sample data with invented staff names — this portal is not connected to the university's timetable system.">
          <div className="space-y-2 text-sm">
            {timetable.map((r, i) => (
              <div key={i} className="flex items-center justify-between glass px-4 py-3">
                <span className="font-mono text-brand-light">{r[0]}</span><span className="flex-1 px-3">{r[1]}</span>
                <span className="text-[var(--muted)] hidden sm:block">{r[2]}</span><span className="ml-3 text-xs glass px-2 py-1">{r[3]}</span>
              </div>
            ))}
          </div>
          <p className="text-xs text-[var(--muted)] mt-3">
            Attendance is recorded in the official SOU MIS; ask your CR or subject faculty
            for corrections.
          </p>
        </Panel>
      )}

      {tab === "Feedback" && <FeedbackPanel />}

      {tab === "Study Plan" && <StudyPanel />}
      {tab === "Tutor" && <TutorPanel />}
      {tab === "Class Group" && <ClassGroupPanel />}
      {tab === "Grievance" && <GrievancePanel />}
      {tab === "Fun Zone" && <FunPanel />}
      {tab === "QR Attendance" && <QRPanel />}
      {tab === "GreenReserve" && <BookingPanel />}
      {tab === "Mark Attendance" && isCR && <CRAttendance assignments={myCr} me={me} />}

      {(tab === "Dashboard" || tab === "Classroom") && (
        <div className={tab === "Dashboard" ? "mt-6" : ""}><ClassroomPanel /></div>
      )}

      {/* The fee figures here were previously hard-coded placeholders. They now
          come from the student's actual fee record, analysed server-side. */}
      {(tab === "Fees") && (
        <>
          <FinancePanel />
          <div className="px-5 max-w-5xl mx-auto">
            <button onClick={downloadReceipt}
              className="px-4 py-2 rounded-full bg-brand text-white text-sm hover:bg-brand-light">
              Download a summary
            </button>
            <p className="text-xs text-[var(--muted)] mt-2">
              For your own reference. An official receipt comes from the Accounts Office —
              this portal does not issue one.
            </p>
          </div>
        </>
      )}

      {tab === "Results" && <ResultsPanel />}

      {tab === "Exams" && (
        <Panel title="Exam timetable" hint="Not connected to the Examination Cell.">
          <p className="text-sm text-[var(--muted)]">
            Timetables, seat allocation and hall tickets are published by the Examination
            Cell and this portal does not hold them — so it shows nothing, rather than a
            placeholder date somebody might plan around.
          </p>
          <p className="text-xs text-[var(--muted)] mt-3">
            Ask OakMitra about examination procedure, or check your class group for
            announcements. Exam Seating, under staff roles, generates seating plans for
            exams the university runs through this system.
          </p>
        </Panel>
      )}

      {tab === "Notes" && (
        <Panel title="Notes & study material"
          hint="Sample entries. Course material is not stored in this system yet.">
          <div className="grid sm:grid-cols-2 gap-3 text-sm">
            {notes.map((n, i) => (
              <button key={i} onClick={() => alert("Sample file — not a real download. Course material is not stored in this system yet.")} className="glass px-4 py-3 flex items-center justify-between text-left hover:bg-brand/10">
                <span>{n[0]}</span><span className="text-xs px-2 py-1 rounded-full bg-brand/20 text-brand-light">{n[1]}</span>
              </button>
            ))}
          </div>
        </Panel>
      )}

      {tab === "My Tickets" && (
        <Panel title="My tickets">
          <button onClick={raise} className="mb-3 px-4 py-2 rounded-full bg-brand text-white text-sm hover:bg-brand-light">+ Raise a Ticket</button>
          <div className="space-y-2 text-sm">
            {mine.map((t) => (
              <div key={t.code} className="glass px-4 py-3 flex items-center justify-between">
                <div><span className="font-mono text-brand-light">{t.code}</span><div className="text-[var(--muted)]">{t.subject}</div>
                  {t.note && <div className="text-xs text-brand-light mt-1">{t.note}</div>}</div>
                <div className="flex items-center gap-2">
                  <span className={`text-xs px-2 py-0.5 rounded-full ${statusColor(t.status)}`}>{t.status}</span>
                  {(t.status === "Resolved" || t.status === "Closed") && <button onClick={() => updateTicket(t.code, { status: "Reopened", note: "Reopened by student" })} className="text-xs px-3 py-1 rounded-full glass">Reopen</button>}
                </div>
              </div>
            ))}
            {mine.length === 0 && <p className="text-[var(--muted)]">You have no tickets. Use the AI assistant or "Raise a Ticket".</p>}
          </div>
        </Panel>
      )}

    </DashboardShell>
  );
}




