/* ============================================================
   Curated help-desk knowledge for retrieval.

   DELIBERATE RULE: these entries describe PROCESS, never figures.
   No fee amounts, dates, deadlines or marks appear here, because
   they are not known to this system and inventing them would be
   worse than saying "ask the office". The IQAC or administration
   should extend this file, or POST additional documents to
   /api/ai/ingest, with the institution's real published values.
   ============================================================ */

export interface KbDoc {
  sourceKey: string;
  sourceType: string;
  title: string;
  content: string;
}

export const KB_DOCS: KbDoc[] = [
  {
    sourceKey: "kb:fees-payment", sourceType: "FAQ", title: "Paying semester fees",
    content: `Semester fees are paid through the university's official fee portal or at the Accounts Office.
Sign in to the student portal, open the Fees section, and follow the payment instructions shown there.
Keep the transaction reference. If a payment is deducted but not reflected within two working days,
raise a ticket from the help desk with the transaction reference attached, and it will be routed to Accounts.

Your own due date and outstanding balance are shown on the Fees page of this portal, against your
individual fee record. This assistant answers from general university documents and therefore does not
hold any particular student's amounts or dates - so for "what do I owe" and "when is mine due", the Fees
page is the place to look, and the Accounts Office publishes the official schedule.`,
  },
  {
    sourceKey: "kb:fee-receipt", sourceType: "FAQ", title: "Fee receipt not generated",
    content: `If a fee receipt has not been generated after payment, first check the Fees section of your portal.
If it is still missing, raise a ticket including the payment date and transaction reference.
Tickets about fees are routed to the Administrative Office and you are notified in the portal and by email.`,
  },
  {
    sourceKey: "kb:exam-timetable", sourceType: "FAQ", title: "Examination timetable and hall ticket",
    content: `Examination timetables and hall tickets are published by the Examination Cell and appear in the
Exams section of your portal. Seat and hall allocation for an examination is generated by the exam cell and
published before the examination date. If your hall ticket is not visible close to the examination, raise a
ticket so the Examination Cell can check your eligibility status.`,
  },
  {
    sourceKey: "kb:results-revaluation", sourceType: "FAQ", title: "Results and revaluation",
    content: `Results are published in the Results section of the portal once released by the examination authority.
If you wish to apply for revaluation or rechecking, follow the process announced by the Examination Cell for that
examination. If a revaluation outcome has not appeared within the announced period, raise a ticket with your
enrollment number and the subject concerned.`,
  },
  {
    sourceKey: "kb:attendance-shortage", sourceType: "FAQ", title: "Attendance and examination eligibility",
    content: `Attendance is recorded per session. In this portal the Class Representative starts an attendance
session, students mark themselves present by scanning a rotating QR code or entering the six-character code shown,
and the faculty member then verifies the batch. Only faculty-verified sessions count.
Universities commonly require a minimum attendance percentage for examination eligibility; the applicable
threshold for your programme is published by the academic office. If you believe your recorded attendance is wrong,
raise a ticket naming the subject and dates.`,
  },
  {
    sourceKey: "kb:qr-attendance-howto", sourceType: "FAQ", title: "How to mark attendance with the QR code",
    content: `Open the QR Attendance section. The Class Representative displays a QR code that changes every twenty
seconds. Scan it with your phone camera, which opens the portal and marks you present, or type the six-character
code shown beside it. You must be signed in on that device. A code that has expired will be refused; ask the CR
for the current one. Faculty approve the session afterwards, and until they do, attendance is not final.`,
  },
  {
    sourceKey: "kb:bonafide-certificate", sourceType: "FAQ", title: "Bonafide certificate and other documents",
    content: `Requests for a bonafide certificate, transcript, transfer certificate or migration certificate are made
through the Administrative Office. Raise a ticket from the help desk stating which document you need and the purpose,
and the request is routed to the Administrative Office. Processing time depends on the document requested.`,
  },
  {
    sourceKey: "kb:id-card", sourceType: "FAQ", title: "Lost or damaged identity card",
    content: `For a lost or damaged identity card, raise a ticket describing what happened. The request is routed to
the Administrative Office, which will advise on the reissue process and any applicable charge.`,
  },
  {
    sourceKey: "kb:hostel", sourceType: "FAQ", title: "Hostel matters",
    content: `Hostel admission, room allocation and maintenance issues are handled by the hostel administration.
Raise a ticket describing the issue, including your block and room number for maintenance requests.
Complaints about hostel facilities can also be raised anonymously through the Grievance channel.`,
  },
  {
    sourceKey: "kb:library", sourceType: "FAQ", title: "Library borrowing and e-resources",
    content: `The library issues and returns books against your identity card. Overdue items may attract a fine set
by the library. Electronic resources and subscribed journals are accessed through the library's own portal.
Library reading rooms, the silent study zone and group discussion pods can be reserved in advance through the
GreenReserve section of this portal.`,
  },
  {
    sourceKey: "kb:greenreserve", sourceType: "FAQ", title: "Booking a room, lab, library seat or facility",
    content: `GreenReserve is the booking system in this portal. Choose a category - classroom, laboratory, library
seat, sports facility, parking, hall or equipment - pick a resource, select the date and time, state the purpose and
the number of attendees, and confirm. Your booking is created as PENDING and an administrator approves or rejects it.
A clash with an existing booking is refused automatically and the conflicting booking's code is shown.
Each booking records its energy use and the carbon avoided by choosing an appropriately sized room.`,
  },
  {
    sourceKey: "kb:grievance", sourceType: "FAQ", title: "Raising a grievance",
    content: `The Grievance channel accepts complaints about academic matters, examinations, fees, infrastructure,
faculty conduct, hostel, harassment and other concerns. Your identity is hidden from the staff who handle the case;
only the Owner can see who filed it, and that identity is encrypted in the database. You receive a tracking code when
you submit - keep it, because it is the only way to follow your case. Use the Track by code tab to see the status and
any response.`,
  },
  {
    sourceKey: "kb:feedback", sourceType: "FAQ", title: "Course feedback",
    content: `Course feedback is anonymous. The system stores a one-way hash of your identity with the form, which
prevents you submitting twice but cannot be reversed to identify you. Feedback is aggregated per subject and faculty
member and is visible to the head of department and above. Individual responses are never attributed.`,
  },
  {
    sourceKey: "kb:scholarship", sourceType: "FAQ", title: "Scholarships and financial aid",
    content: `Scholarship and freeship applications follow the schedule announced by the scholarship cell and the
relevant government portal. If a sanctioned scholarship amount has not been credited, raise a ticket with your
application reference so it can be routed to Accounts.`,
  },
  {
    sourceKey: "kb:placement", sourceType: "FAQ", title: "Placements and internships",
    content: `Placement drives, eligibility criteria and internship opportunities are announced by the training and
placement cell. Questions about eligibility for a specific company, or about an offer you have received, are personal
to your record and are raised as a ticket rather than answered here.`,
  },
  {
    sourceKey: "kb:wifi-it", sourceType: "FAQ", title: "Campus network and IT problems",
    content: `For campus Wi-Fi, portal access or laboratory computer problems, raise a ticket describing the block,
floor and the time the problem occurs. Network issues affecting a whole area are more useful to report with that
detail than as a general complaint.`,
  },
  {
    sourceKey: "kb:portal-login", sourceType: "FAQ", title: "Signing in to the portal",
    content: `Sign in with your login ID, which is your enrollment number for students, and your password.
If you have never set a password, enter your date of birth once and you will immediately be asked to choose one.
Passwords must be at least ten characters and include an uppercase letter, a lowercase letter and a number.
They may not contain your login ID and may not be a date. After five failed attempts an account locks for fifteen
minutes. Date of birth is no longer accepted once a password has been set.`,
  },
  {
    sourceKey: "kb:iqac", sourceType: "FAQ", title: "IQAC and accreditation evidence",
    content: `The IQAC section holds quality criteria, indicators and metrics as editable records, along with an
evidence vault. Evidence is uploaded against a metric for an academic year, verified by an administrator or head of
department, and then approved by the IQAC. Approval requires prior verification, and the role that verifies is not
the role that approves. Reports are generated only from approved evidence, and every statement links to the records
behind it. This system does not calculate or predict any accreditation outcome.`,
  },
  {
    sourceKey: "kb:tickets", sourceType: "FAQ", title: "How tickets work",
    content: `When this assistant cannot answer confidently, or when a question concerns your personal record, a
ticket is created and routed to the appropriate office. You can see your tickets in the portal and you are notified
there and by email when there is a response. Include specific details - dates, subject names, reference numbers -
because tickets with detail are resolved faster.`,
  },
  {
    sourceKey: "kb:contact", sourceType: "FAQ", title: "Contacting the help desk by phone",
    content: `If a query is urgent or cannot be resolved in the portal, the help desk telephone numbers are
079-35201300, 079-66046300 and +91 9099063464.`,
  },
];
